---
title: "Figures - Trajectories"
author: "Joe Brown"
date: "2025-06-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Calculate summaries 

Exp 2:
```{r}
co2_summary_exp2 <- weighted_result_exp2_df %>% 
  subset(variable == "CO2_concentration" & year < 2101) %>% 
  group_by(scenario, year) %>% 
  dplyr::summarize(median = weighted.quantile(value, w = mc_weight, probs = c(0.5)), 
            ci_05 = weighted.quantile(value, w = mc_weight, probs = c(0.05)), 
            ci_95 = weighted.quantile(value, w = mc_weight, probs = c(0.95)), 
          .groups = "drop") %>% 
  mutate(config = "concentration-emission")
  
```

Exp 3:
```{r}
co2_summary_exp3 <- weighted_result_exp3_df %>% 
  subset(variable == "CO2_concentration" & year < 2101) %>% 
  group_by(scenario, year) %>% 
  dplyr::summarize(median = weighted.quantile(value, w = mc_weight, probs = c(0.5)), 
            ci_05 = weighted.quantile(value, w = mc_weight, probs = c(0.05)), 
            ci_95 = weighted.quantile(value, w = mc_weight, probs = c(0.95)), 
          .groups = "drop") %>% 
  mutate(config = "emission")
  
```


combine all the co2 data:

```{r}

combined_co2 <- rbind(co2_summary_exp2, co2_summary_exp3)

```


combine the constrinat data
```{r}
## Load CO2 data for constraint

# scenario names
ssp_scenarios <- c("ssp119", "ssp126", "ssp245", "ssp370", "ssp585")
# directory where constraint data are saved
constraint_dir <- here("data", "processed")

# Load scenario specific co2 constraint data
constraint_data_list <- lapply(ssp_scenarios, function(ssp) {
  
  read.csv(file.path(constraint_dir, paste0(ssp, "_CO2_constraint-full.csv")))
  
})

# edit list names
names(constraint_data_list) <- names(ini_list)

# Add scenario name as a column to each constraint data frame
constraint_data_list <- Map(function(df, scen_name) {
  df$scenario <- scen_name
  return(df)
}, constraint_data_list, names(constraint_data_list))


constraint_data <- do.call(rbind, constraint_data_list)

constraint_data <- subset(constraint_data, year >= 1850 & year <= 2100)

constraint_data$config <- "concentration"
```

# Plotting 

```{r}
combined_levels <- c("concentration", "concentration-emission", "emission")

constraint_data$config <- factor(constraint_data$config, levels = combined_levels)
combined_co2$config <- factor(combined_co2$config, levels = combined_levels)

# Default ggplot2 palette for discrete colors (first 3)
default_colors <- c("#F8766D", "#7CAE00", "#00BFC4")  # These are the default ggplot2 colors
names(default_colors) <- c("concentration", "concentration-emission", "emission")

ggplot() +
  geom_line(data = combined_co2, 
            aes(x = year, y = median, color = config), 
            linewidth = 0.5) +
  geom_ribbon(data = combined_co2, 
              aes(x = year, ymin = ci_05, ymax = ci_95, fill = config), 
              alpha = 0.2) +
    geom_line(data = constraint_data,
            aes(x = year, y = CO2_constrain, color = config),
            linewidth = 0.8, linetype = "dashed") +
  facet_wrap(~scenario) +
  scale_color_manual(values = default_colors) +
  scale_fill_manual(values = default_colors) +
  guides(alpha = "none") +
  theme_light()
ggsave("co2_projection_comparison.png")
```

# Calculate summaries 

Exp 2:
```{r}
gsat_summary_exp2 <- weighted_result_exp2_df %>% 
  subset(variable == "global_tas" & year < 2101) %>% 
  group_by(scenario, year) %>% 
  dplyr::summarize(median = weighted.quantile(value, w = mc_weight, probs = c(0.5)), 
            ci_05 = weighted.quantile(value, w = mc_weight, probs = c(0.05)), 
            ci_95 = weighted.quantile(value, w = mc_weight, probs = c(0.95)), 
          .groups = "drop") %>% 
  mutate(config = "concentration-emission")
  
```

Exp 3:
```{r}
gsat_summary_exp3 <- weighted_result_exp3_df %>% 
  subset(variable == "global_tas" & year < 2101) %>% 
  group_by(scenario, year) %>% 
  dplyr::summarize(median = weighted.quantile(value, w = mc_weight, probs = c(0.5)), 
            ci_05 = weighted.quantile(value, w = mc_weight, probs = c(0.05)), 
            ci_95 = weighted.quantile(value, w = mc_weight, probs = c(0.95)), 
          .groups = "drop") %>% 
  mutate(config = "emission")
  
```


Exp 1:
```{r}

gsat_summary_exp1 <- weighted_result_exp1_df %>% 
  subset(variable == "global_tas" & year < 2101) %>% 
  group_by(scenario, year) %>% 
  dplyr::summarize(median = weighted.quantile(value, w = mc_weight, probs = c(0.5)), 
            ci_05 = weighted.quantile(value, w = mc_weight, probs = c(0.05)), 
            ci_95 = weighted.quantile(value, w = mc_weight, probs = c(0.95)), 
          .groups = "drop") %>% 
  mutate(config = "concentration")

```

```{r}
combined_gsat <- rbind(gsat_summary_exp1, gsat_summary_exp2, gsat_summary_exp3)
```


# Plotting 

```{r}

# Default ggplot2 palette for discrete colors (first 3)
default_colors <- c("#F8766D", "#7CAE00", "#00BFC4")  # These are the default ggplot2 colors
names(default_colors) <- c("concentration", "concentration-emission", "emission")

ggplot() +
  geom_line(data = combined_gsat, 
            aes(x = year, y = median, color = config), 
            linewidth = 0.5) +
  geom_line(data = combined_gsat, 
            aes(x = year, y = ci_05, color = config), 
            linetype = "dotted", linewidth = 0.4) +
  geom_line(data = combined_gsat, 
            aes(x = year, y = ci_95, color = config), 
            linetype = "dotted", linewidth = 0.4) +
  facet_wrap(~scenario) +
  scale_color_manual(values = default_colors) +
  theme_light()
ggsave("gsat_projection_comparison.png", height = 10, width = 15)
```